# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{executioner}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eloy Duran"]
  s.date = %q{2011-09-17}
  s.description = %q{Execute CLI utilities}
  s.email = %q{eloy@fngtps.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".kick",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION.yml",
    "executioner.gemspec",
    "lib/executioner.rb",
    "test/executioner_test.rb",
    "test/scripts/load_executioner_without_home.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{http://fingertips.github.com}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Execute CLI utilities}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<open4>, ["~> 1.1.0"])
    else
      s.add_dependency(%q<open4>, ["~> 1.1.0"])
    end
  else
    s.add_dependency(%q<open4>, ["~> 1.1.0"])
  end
end

