# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{executioner}
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eloy Duran"]
  s.date = %q{2011-04-21}
  s.description = %q{Execute CLI utilities}
  s.email = %q{eloy@fngtps.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     ".kick",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "executioner.gemspec",
     "lib/executioner.rb",
     "test/executioner_test.rb",
     "test/scripts/load_executioner_without_home.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://fingertips.github.com}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Execute CLI utilities}
  s.test_files = [
    "test/executioner_test.rb",
     "test/scripts/load_executioner_without_home.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

